name: chat_app
description: ST Promoter Hub (Flet + Flutter)
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase & notifications
  firebase_core: ^2.24.0
  firebase_messaging: ^14.7.0
  flutter_local_notifications: ^16.3.0
  shared_preferences: ^2.2.2

  # Helpers
  path_provider: ^2.0.15
  permission_handler: ^11.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.1

flutter:
  uses-material-design: true

  # IMPORTANT â€” include the service account here so it's packaged into the APK
  assets:
    - assets/firebase_service_account.json
    # (optional, but fine to include the icon as an asset too)
    - assets/chat_app_icon.png

  fonts:
    - family: MaterialIcons
      fonts:
        - asset: assets/fonts/MaterialIcons-Regular.otf

# Run `flutter pub run flutter_launcher_icons` after updating this configuration.
flutter_icons:
  android: true
  ios: false
  image_path: "assets/chat_app_icon.png"
  min_sdk_android: 23
